### ISSUE TITLE
rtl8192ee bluetooth

### ISSUE THREAD

**Issue by JoeyAndres** [lwfinger/rtlwifi_new#58]
Hello and many thanks to your work.

I have bought a Lenovo L540 months ago. I've look at my invoice and 
```
WiFi wireless LAN adapters 	ThinkPad b/g/n BT
```
meaning there should be a bluetooth. I never tested the windows os that came with it (immediately replaced it with ubuntu 14.04, now upgraded to 15.04 w/ kernel 4.1).

I installed your package along with the bios update to make the wifi work flawlessly. Now that some system background is mentioned, when I try to connect to bluetooth via gui interface of ubuntu I get **adapter not found**. Doing the following command ```dmesg | tail``` I get:
```
[   41.453495] usb 1-11: No LPM exit latency info found, disabling LPM.
[   41.454553] usb 1-11: New USB device found, idVendor=0bda, idProduct=8761
[   41.454556] usb 1-11: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   41.454558] usb 1-11: Product: Bluetooth Radio
[   41.454559] usb 1-11: Manufacturer: Realtek
[   41.454561] usb 1-11: SerialNumber: 00e04c000001
[   41.468873] Bluetooth: hci0: rtl: examining hci_ver=06 hci_rev=000a lmp_ver=06 lmp_subver=8761
[   41.468876] Bluetooth: hci0: rtl: loading rtl_bt/rtl8761a_fw.bin
[   41.468904] usb 1-11: Direct firmware load for rtl_bt/rtl8761a_fw.bin failed with error -2
[   41.468905] Bluetooth: hci0: Failed to load rtl_bt/rtl8761a_fw.bin
```

**Comment by lwfinger** [comment]
You need to install the firmware just as the dmesg output says.

Clone http://github.com/lwfinger/rtl8723au_bt.git and select the "kernel" branch.After you cd to that directory, "make", and "sudo make install", then the firmware will be installed along with a driver that I know works. When kernel 4.2 comes out, it will work without needing this repo, but earlier kernels do.

**Comment by JoeyAndres** [comment]
joey@jandres-linux-01:~$ dmesg | tail
[   56.425002] usb 1-11: new full-speed USB device number 6 using xhci_hcd
[   56.552388] usb 1-11: No LPM exit latency info found, disabling LPM.
[   56.553508] usb 1-11: New USB device found, idVendor=0bda, idProduct=8761
[   56.553512] usb 1-11: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[   56.553514] usb 1-11: Product: Bluetooth Radio
[   56.553516] usb 1-11: Manufacturer: Realtek
[   56.553517] usb 1-11: SerialNumber: 00e04c000001
[   56.568767] Bluetooth: hci0: hci_ver=06 hci_rev=000a lmp_ver=06 lmp_subver=8761
[   56.568826] btusb: Loaded firmware rtl_bt/rtl8761a_fw.bin
[   56.569758] Bluetooth: firmware is for 8821 but this is a 8761

**Comment by lwfinger** [comment]
I just pushed replacement firmware. I hope this one works. Apparently, you are the first 8761 user.

**Comment by JoeyAndres** [comment]
I still get same message from ```dmesg | tail```. I then  looked for the message "firmware is for " and uncomment the whole block in **btusb.c**,

```c
if (lmp_subver != project_id_to_lmp_subver[project_id]) {
	  BT_ERR("firmware is for %x but this is a %x",
		 project_id_to_lmp_subver[project_id], lmp_subver);
	  return -EINVAL;
	}
```

**Comment by lwfinger** [comment]
I added some additional printout to the error message. Do a 'git pull', "make", "sudo make install", and then unload and reload the driver. Then post the last part of dmesg again.

**Comment by JoeyAndres** [comment]
[  285.205711] usbcore: registered new interface driver btusb
[  285.207011] Bluetooth: hci0: hci_ver=06 hci_rev=000a lmp_ver=06 lmp_subver=8761
[  285.207084] btusb: Loaded firmware rtl_bt/rtl8761a_fw.bin
[  285.207986] Bluetooth: firmware is for 8821 but this is a 8761, project_id is 3

**Comment by lwfinger** [comment]
I found a bug. Does this fix your problem?

**Comment by JoeyAndres** [comment]
It fixes the loading of the module. I still have the second error as described above.

**Comment by JoeyAndres** [comment]
I switched to fedora, where bluez 5.x is installed and it now works.

**Comment by lwfinger** [comment]
Thanks for letting me know that it works with Fedora. It also works with openSUSE 13.2, which is what I use. It has bluez version 5.23. I will now know to ask what version of bluez is installed.
