### ISSUE TITLE
[rtw88] Fixing make uninstall

### ISSUE THREAD

**Issue by URemery** [lwfinger/rtlwifi_new#613]
Hi,

I found that `sudo make uninstall` doesn't work properly. Actually it tries to remove any _.ko_ files in the module directory but there only _.ko.gz_ or _.ko.xz_ files in it.

So here's a patch to fix this issue : [fixed-make-uninstall.patch.txt](https://github.com/lwfinger/rtlwifi_new/files/4770707/fixed-make-uninstall.patch.txt).

I'm not sure that's the right place to share this patch, feel free to show me a more appropriate way to do it :)

PS : I tried to build the driver just like iaissaoui in issue #608. Had the same errors

**Comment by lwfinger** [comment]
Thanks for the notification. Rather than removing rtw*, I would prefer removing rtw88*.ko*, etc. I have pushed that change.

**Comment by iaissaoui** [comment]
Looks like the uninstall section in the makefile is still the same in rtw88
I think it is missing this as well

`@modprobe -r rtw_8821ce`

and rtw_core deletion will always fail because the script is deleting rtw_* beforehand

**Comment by lwfinger** [comment]
Yes, I have been concentrating on fixing the rtw8821ce driver so that it does not crash the kernel. I will look at this comment later.
