### ISSUE TITLE
RTL8821AE 5G unusable, found backtrace in dmesg

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [lwfinger/rtlwifi_new#89]
**kernel** "4.3.3-2-ARCH #1 SMP PREEMPT Wed Dec 23 20:09:18 CET 2015 x86_64 GNU/Linux"
**os** archlinux
I can connect to an 5G hotspot (by network manager), can get an address from DHCP, but after that even the gateway is unreachable. 
found a backtrace reported by network manager in dmesg, it is here https://gist.github.com/Alkaid-Benetnash/2d7e8378d010d4bccad1
by the way, switch to an 2.4G hotspot ( created by the same router ) works at once.
PS: I changed an option of module rtl8821ae : msi=0, due to the CPU softlock described in https://github.com/lwfinger/rtlwifi_new/issues/64

**Comment by tgharib** [comment]
Hi,

I have the same issue with RTL8812AE. I found a workaround here: https://github.com/lwfinger/rtlwifi_new/issues/56#issuecomment-172944778

**Comment by Alkaid-Benetnash** [comment]
@tgharib thank you for providing more information, but that workaround not work.
actually, there is no "disable" in my "iw phy", here is it output https://gist.github.com/Alkaid-Benetnash/a256ff277ec8744d8e75

now I update to kernel 4.4.1-2-ARCH, something is different, though I still unable to connect to 5G AP

1.     can detect 5G AP in network-manager pannel
2.     no more backtrace in "dmesg"
3.     can't get an address by DHCP
4.     when attempt to connect a 5G AP, I get an authentication timeout, but the time interval is quite short. network-manager log pasted below

[ 3574.280580] wlp4s0: authenticate with 80:89:17:56:d7:68
[ 3574.281094] wlp4s0: send auth to 80:89:17:56:d7:68 (try 1/3)
[ 3574.382974] wlp4s0: send auth to 80:89:17:56:d7:68 (try 2/3)
[ 3574.486325] wlp4s0: send auth to 80:89:17:56:d7:68 (try 3/3)
[ 3574.589650] wlp4s0: authentication with 80:89:17:56:d7:68 timed out

**Comment by lwfinger** [comment]
The backtrace reported in #56 has been fixed in mainline as commit c72fc9093718. That fix has probably not been propagated to ARCH kernels yet, although it will likely be available there eventually.

This particular bug has been fixed in all branches of this repo, thus code from here should work.

**Comment by Alkaid-Benetnash** [comment]
I tried the latest mainline kernel 4.5-rc3, wifi behaves like the very beginning. can connect after a long time, but can't even reach the gateway. 
however, similar backtrace still exists in dmesg
please view the dmesg of kernel 4.5-rc3 here again( it is the second file
https://gist.github.com/Alkaid-Benetnash/2d7e8378d010d4bccad1#file-rtl8821ae-5g-backtrace-with-kernel-4-5-rc3

**Comment by lwfinger** [comment]
The patch has been submitted to mainline and exists in wireless-drivers-next, but has not yet propagated to mainline. It should make its way through the system by the time 4.5 is released, but there are no promises; however, as the problem was reported by Linus Torvalds, and the patch was tested by him, it should be in mainline soon. In the meantime, use this repo, which has been more quickly fixed.

**Comment by lwfinger** [comment]
A completely new version of the drivers has just been pushed. It fixes a lot of things. As a result, I am closing all open issues. If you get a new one, please create a new issue.

Note: The new driver fixes the problems with power save. It is recommended that you clear all ips, swlps, and fwlps options.
